// layout.js

import { Inter } from "next/font/google";
import "./globals.css"; // Import your global CSS file
// import Footer from "@/components/footer/Footer";
// import { ThemeContextProvider } from "@/context/ThemeContext";
// import ThemeProvider from "@/providers/ThemeProvider";

// import Featured from "@/components/featured/Featured";
// import CategoryList from "@/components/categoryList/CategoryList";
// import AuthProvider from "@/providers/AuthProvider";
import Navbar from "./comonents/navbar/Navbar";
import { ThemeContextProvider } from "./context/ThemeContext";
import ThemeProvider from "./providers/ThemeProvider";
import AuthProvider from "./providers/AuthProvider";
import Footer from "./comonents/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeContextProvider>
            <ThemeProvider>
              {/* <Navbar/> */}
              <Navbar />
              {children}
              <Footer/>
              {/* <Footer /> */}
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
